local C = _G.__unaliveui_creator.Create; local blur = _G.__unaliveui_blur
return function(self, props)
	props = props or {}; props.Title = props.Title or "UnAlive"; props.Description = props.Description or ""; props.Buttons = props.Buttons or {}
	local dark = Color3.fromRGB(18, 20, 26); local white = Color3.fromRGB(255, 255, 255)
	local body = C("Frame")({ Name = "Alert", BackgroundTransparency = 1, Size = UDim2.fromOffset(260, 140),
		C("Frame")({ Name = "Shadow", Size = UDim2.new(1, 4, 1, 4), Position = UDim2.fromOffset(-2, -2), BackgroundColor3 = Color3.fromRGB(0, 0, 0), BackgroundTransparency = 0.78, BorderSizePixel = 0, ZIndex = 98, C("UICorner")({ CornerRadius = UDim.new(0, 26) }) }),
		C("Frame")({ Name = "Background", Size = UDim2.fromScale(1, 1), BackgroundColor3 = dark, BackgroundTransparency = 0.08, BorderSizePixel = 0, ZIndex = 100, C("UICorner")({ CornerRadius = UDim.new(0, 26) }), C("UIStroke")({ Color = white, Transparency = 0.88, Thickness = 1 }) }),
		C("Frame")({ Name = "BlurPane", Size = UDim2.new(1, -20, 1, -20), Position = UDim2.fromOffset(10, 10), BackgroundTransparency = 1, BorderSizePixel = 0, ZIndex = 99 }),
	})
	local bg = body.__instance:FindFirstChild("Background"); local blurPane = body.__instance:FindFirstChild("BlurPane")
	if blur and blurPane then task.spawn(function() blur(blurPane) end) end
	local titleLbl = Instance.new("TextLabel"); titleLbl.Size = UDim2.fromOffset(216, 16); titleLbl.Position = UDim2.fromOffset(22, 20); titleLbl.BackgroundTransparency = 1; titleLbl.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Bold); titleLbl.Text = props.Title; titleLbl.TextSize = 13; titleLbl.TextColor3 = white; titleLbl.TextXAlignment = Enum.TextXAlignment.Left; titleLbl.TextYAlignment = Enum.TextYAlignment.Center; titleLbl.RichText = true; titleLbl.ZIndex = 102; titleLbl.Parent = bg
	local descLbl = Instance.new("TextLabel"); descLbl.Size = UDim2.fromOffset(216, 28); descLbl.Position = UDim2.fromOffset(22, 46); descLbl.BackgroundTransparency = 1; descLbl.FontFace = Font.new("rbxassetid://12187365364"); descLbl.Text = props.Description; descLbl.TextSize = 11; descLbl.TextColor3 = Color3.fromRGB(180, 180, 190); descLbl.TextXAlignment = Enum.TextXAlignment.Left; descLbl.TextYAlignment = Enum.TextYAlignment.Top; descLbl.RichText = true; descLbl.ZIndex = 102; descLbl.Parent = bg
	for i, btnData in ipairs(props.Buttons) do local x = 16 + (i - 1) * 118; local dest = btnData.Destructive or false; local btn = Instance.new("TextButton"); btn.AutoButtonColor = false; btn.Size = UDim2.fromOffset(110, 32); btn.Position = UDim2.fromOffset(x, 92); btn.BackgroundTransparency = 1; btn.BorderSizePixel = 0; btn.Text = ""; btn.ZIndex = 102; btn.Parent = bg; Instance.new("UICorner", btn).CornerRadius = UDim.new(1, 0)
		local btnBg = Instance.new("Frame"); btnBg.Size = UDim2.fromScale(1, 1); btnBg.BorderSizePixel = 0; btnBg.ZIndex = 101; btnBg.BackgroundColor3 = dest and Color3.fromRGB(255, 56, 60) or Color3.fromRGB(230, 230, 230); btnBg.BackgroundTransparency = dest and 0.77 or 0; btnBg.Parent = btn; Instance.new("UICorner", btnBg).CornerRadius = UDim.new(1, 0)
		local btnLbl = Instance.new("TextLabel"); btnLbl.Size = UDim2.fromScale(1, 1); btnLbl.BackgroundTransparency = 1; btnLbl.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Medium); btnLbl.Text = btnData.Label; btnLbl.TextSize = 13; btnLbl.TextColor3 = dest and Color3.fromRGB(255, 56, 60) or Color3.fromRGB(0, 0, 0); btnLbl.TextXAlignment = Enum.TextXAlignment.Center; btnLbl.TextYAlignment = Enum.TextYAlignment.Center; btnLbl.ZIndex = 102; btnLbl.Parent = btn
		if btnData.Pushed then btn.MouseButton1Click:Connect(function() task.spawn(btnData.Pushed) end) end
	end
	local obj = { Type = "Alert", __instance = body.__instance }; function obj.Parent(p) body.Parent = p end; function obj:SetTitle(v) titleLbl.Text = v end; function obj:SetDescription(v) descLbl.Text = v end; return obj
end